travis:
  secure:
    BINSTAR_TOKEN: izRTjZNINAc5YsRYb3I5uo+VjALBWuZH4OVeaeQKRQIFQoyAAHURcY4WA11/rdhJqUchDLw50vRwrbuh2zjKjw8U/JKXlN3jk58rORpj5uQplHHA0ieMi5ob1J4QHWu3NLZrQVqKe1CZiuhFnvlwZi0nXJu/D+ojL2oBBefVYuzNTnrSdTZLiUDDfaofnEH4Om+mdCiTjCPwu2Yc2D8WhPUEF4KQ5x3lKkPNY+ieawQsq41GduCeGAI9n3n6QRJ2h917rVdl/5wdda9WV741wfxtMmIc2CmP42sbLf2eG36EDn2lt3ExAXJhj8ZAislhkpmqe8KYpHHwFsMvR5S2w6jFWkG8slPQujNKZLvuOWdIlp7PbxbjJ4a5//H2EnHTzt7eibPXm28pElWMvcj0yxn9rBqGSoiDFBBFEte/He3U1J6svduKZOdH3aKNBpzZo3F6V29s/PaQ0DlgZUBfk/wqmkjQa/hPgUlERmRGgWS60E+q2gWz6Q6+ooBpr9d26rzotLX3vHrvHfonNRviMOU2KWxSZr7FSKk2U451T2IdoUziXUGZFN8E5VYiYwUdQUO9oA9aDvQmEw2aW62yktgiosvGuzeA2pZO0cjRE4P2lN31bs1yrMZlFwBk0ddf2N9QdsL1ZzhCTeW3Kp8TCyfWhOJEbt9eipQax2Js07E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
